version: "3.9"

services:

  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_USER: drkiq
      POSTGRES_PASSWORD: test_db_password
    ports: 
      - '5432:5432'
    volumes:
      - drkiq-postgres:/var/lib/postgresql/data

  redis:
    image: redis:7.0
    ports:
      - '6379:6379'
    volumes:
      - drkiq-redis:/var/lib/redis/data

  drkiq:
    image: drkiq:latest
    environment:
      REDIS_URL: xxx:6379
      AWS_ACCESS_KEY_ID: 
      AWS_SECRET_ACCESS_KEY: 
      AWS_DEFAULT_REGION: 
      ELASTICSEARCH_USERNAME: 
      ELASTICSEARCH_PASSWORD: 
      ELASTICSEARCH_URL: 
    volumes:
      - ./drkiq:/opt/app
    links:
      - postgres
      - redis
    ports:
      - '8010:8010'
    env_file:
      - .env

  sidekiq:
    image: sidekiq:latest
    links:
      - postgres
      - redis
    env_file:
      - .env

volumes:
  drkiq-postgres:
  drkiq-redis:
