version: "3.9"

services:

  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_USER: drkiq
      POSTGRES_PASSWORD: test_db_password
    ports: 
      - '5432:5432'
    volumes:
      - drkiq-postgres:/var/lib/postgresql/data

  redis:
    image: redis:7.0
    ports:
      - '6379:6379'
    volumes:
      - drkiq-redis:/var/lib/redis/data

  drkiq:
    image: drkiq:latest
    environment:
      REDIS_URL: redis://rediscluster.ouzkgr.clustercfg.use1.cache.amazonaws.com:6379
      AWS_ACCESS_KEY_ID: AKIA4L57F4CKZHFPZOU4
      AWS_SECRET_ACCESS_KEY: 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
      AWS_DEFAULT_REGION: us-east-1
      ELASTICSEARCH_USERNAME: admin
      ELASTICSEARCH_PASSWORD: Barbarbarbar1!
      ELASTICSEARCH_URL: https://search-railssearch-ru2qys7sfy3euvqtg53ad42jky.us-east-1.es.amazonaws.com
    volumes:
      - ./drkiq:/opt/app
    links:
      - postgres
      - redis
    ports:
      - '8010:8010'
    env_file:
      - .env

  sidekiq:
    image: sidekiq:latest
    links:
      - postgres
      - redis
    env_file:
      - .env

volumes:
  drkiq-postgres:
  drkiq-redis:
